import type { Communication } from "@/lib/communication-types"

const now = new Date().toISOString()
const hour = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
const day = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString()

export const COMMUNICATION_SEED_DATA: Communication[] = [
  {
    id: "comm-1",
    channel: "email",
    subject: "Quote request for lawn maintenance",
    body: "Hi, we'd like a quote for monthly lawn care and hedge trimming for our property at 12 Oak Lane. Please let us know availability and pricing. Thanks, James Wilson",
    contactName: "James Wilson",
    contactId: "seed-1",
    contactEmail: "james.wilson@greenviewestates.co.uk",
    contactPhone: "+44 7700 900123",
    direction: "inbound",
    read: false,
    createdAt: hour(2),
  },
  {
    id: "comm-2",
    channel: "sms",
    subject: "",
    body: "Thanks for the estimate. We'll get back to you by Friday.",
    contactName: "Sarah Mitchell",
    contactId: "seed-2",
    contactPhone: "+44 161 234 5678",
    direction: "inbound",
    read: true,
    createdAt: hour(5),
  },
  {
    id: "comm-3",
    channel: "call",
    subject: "Follow-up call",
    body: "Discussed project timeline and deposit. Customer agreed to start next week.",
    contactName: "David Thompson",
    contactId: "seed-3",
    contactPhone: "+44 121 456 7890",
    direction: "outbound",
    read: true,
    createdAt: day(1),
  },
  {
    id: "comm-4",
    channel: "email",
    subject: "Re: Garden design proposal",
    body: "We've reviewed the proposal and would like to proceed with Phase 1. When can you schedule the initial site visit?",
    contactName: "Emma Collins",
    contactId: "seed-4",
    contactEmail: "emma@collinsgardens.co.uk",
    direction: "inbound",
    read: false,
    createdAt: day(1),
  },
  {
    id: "comm-5",
    channel: "sms",
    subject: "",
    body: "Crew arrived. Gate code is 4521.",
    contactName: "Michael Roberts",
    contactId: "seed-5",
    contactPhone: "+44 113 496 0123",
    direction: "inbound",
    read: true,
    createdAt: day(2),
  },
  {
    id: "comm-6",
    channel: "email",
    subject: "Invoice #10234 payment confirmation",
    body: "Payment received. Thank you for your business.",
    contactName: "Rachel Green",
    contactId: "seed-6",
    contactEmail: "rachel.green@outlook.com",
    direction: "outbound",
    read: true,
    createdAt: day(2),
  },
  {
    id: "comm-7",
    channel: "call",
    subject: "Site survey booking",
    body: "Booked site survey for Thursday 2pm. Main contact: Oliver Harris.",
    contactName: "Oliver Harris",
    contactId: "seed-7",
    contactPhone: "+44 29 2087 4000",
    direction: "outbound",
    read: true,
    createdAt: day(3),
  },
  {
    id: "comm-8",
    channel: "email",
    subject: "Seasonal service renewal",
    body: "Hi Sophie, your seasonal maintenance is due for renewal. We're offering 10% off if you confirm by end of month. Let us know if you have any questions.",
    contactName: "Sophie Turner",
    contactId: "seed-8",
    contactEmail: "sophie.turner@gmail.com",
    direction: "outbound",
    read: false,
    createdAt: day(3),
  },
  {
    id: "comm-9",
    channel: "sms",
    subject: "",
    body: "Job completed. Please confirm you're happy with the result.",
    contactName: "James Clark",
    contactId: "seed-9",
    contactPhone: "+44 131 226 7000",
    direction: "outbound",
    read: true,
    createdAt: day(4),
  },
  {
    id: "comm-10",
    channel: "email",
    subject: "New enquiry - Clifton project",
    body: "We're interested in a full garden redesign including patio and planting. Property is 4 Clifton Down, Bristol. Can you send a brochure and rough cost range?",
    contactName: "Lucy Bennett",
    contactId: "seed-10",
    contactEmail: "lucy@bennettlandscapes.co.uk",
    direction: "inbound",
    read: false,
    createdAt: day(4),
  },
  {
    id: "comm-11",
    channel: "call",
    subject: "Complaint follow-up",
    body: "Customer reported one border not edged. Arranged return visit next Tuesday.",
    contactName: "Daniel Wright",
    contactId: "seed-11",
    contactPhone: "+44 115 948 3344",
    direction: "outbound",
    read: true,
    createdAt: day(5),
  },
  {
    id: "comm-12",
    channel: "email",
    subject: "Q2 commercial maintenance schedule",
    body: "Please find attached the proposed schedule for Q2. Let me know if any dates need to move.",
    contactName: "Chloe Adams",
    contactId: "seed-12",
    contactEmail: "chloe@adamsproperty.co.uk",
    direction: "inbound",
    read: true,
    createdAt: day(5),
  },
  {
    id: "comm-13",
    channel: "sms",
    subject: "",
    body: "Are you able to do a quote this week? Need it for insurance claim.",
    contactName: "Thomas King",
    contactId: "seed-13",
    contactPhone: "+44 161 834 7788",
    direction: "inbound",
    read: false,
    createdAt: day(6),
  },
  {
    id: "comm-14",
    channel: "email",
    subject: "Bulk order - plants and mulch",
    body: "Confirming order for 50 shrubs and 20 cubic metres mulch. Delivery to Lewes Road site. Invoice to follow.",
    contactName: "Hannah Phillips",
    contactId: "seed-14",
    contactEmail: "hannah@phillipsnurseries.co.uk",
    direction: "inbound",
    read: true,
    createdAt: day(6),
  },
  {
    id: "comm-15",
    channel: "call",
    subject: "Weather delay",
    body: "Called to reschedule due to rain. New date: next Monday.",
    contactName: "William Foster",
    contactId: "seed-15",
    contactPhone: "+44 23 8063 2211",
    direction: "outbound",
    read: true,
    createdAt: day(7),
  },
]
