import type { Customer } from "@/lib/customer-types"

const now = new Date().toISOString()
const lastWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
const lastMonth = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()

export const CUSTOMER_SEED_DATA: Customer[] = [
  {
    id: "seed-1",
    name: "James Wilson",
    companyName: "Green View Estates Ltd.",
    phones: ["+44 7700 900123"],
    emails: ["james.wilson@greenviewestates.co.uk"],
    addresses: ["12 Kensington High Street, London W8 4PT"],
    tags: ["residential", "premium", "repeat"],
    leadSource: "referral",
    partnerReferralName: "London Property Hub",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [
      {
        id: "n1",
        content: "Requested quarterly lawn maintenance. Prefers organic products.",
        createdAt: lastWeek,
        createdBy: "Support",
      },
    ],
    timeline: [
      {
        id: "t1",
        type: "communication",
        title: "Initial call",
        date: lastMonth,
        description: "Discussed lawn design and maintenance plan.",
      },
    ],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-2",
    name: "Sarah Mitchell",
    companyName: "Mitchell & Sons Trading",
    phones: ["+44 161 234 5678"],
    emails: ["sarah.mitchell@mitchelltrading.co.uk"],
    addresses: ["45 Deansgate, Manchester M3 2BW"],
    tags: ["commercial", "warehouse"],
    leadSource: "LinkedIn",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-3",
    name: "David Thompson",
    companyName: "",
    phones: ["+44 121 456 7890"],
    emails: ["david.thompson@gmail.com"],
    addresses: ["Block 7, Flat 3, Edgbaston, Birmingham B15 2TR"],
    tags: ["residential"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-4",
    name: "Emma Collins",
    companyName: "Collins Garden Design",
    phones: ["+44 20 7946 0958"],
    emails: ["emma@collinsgardens.co.uk"],
    addresses: ["88 Chelsea Embankment, London SW3 4LE"],
    tags: ["residential", "design"],
    leadSource: "referral",
    partnerReferralName: "Garden Society",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-5",
    name: "Michael Roberts",
    companyName: "Roberts Retail Group",
    phones: ["+44 113 496 0123"],
    emails: ["m.roberts@robertsretail.co.uk"],
    addresses: ["Unit 14, Leeds Industrial Park, LS10 1AB"],
    tags: ["commercial", "repeat"],
    leadSource: "LinkedIn",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-6",
    name: "Rachel Green",
    companyName: "",
    phones: ["+44 141 552 3456"],
    emails: ["rachel.green@outlook.com"],
    addresses: ["22 Byres Road, Glasgow G11 5JY"],
    tags: ["residential"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-7",
    name: "Oliver Harris",
    companyName: "Harris Hotels Ltd",
    phones: ["+44 29 2087 4000", "+44 29 2087 4001"],
    emails: ["facilities@harrishotels.co.uk"],
    addresses: ["1 Cathedral Road, Cardiff CF11 9SD"],
    tags: ["commercial", "premium"],
    leadSource: "partner",
    partnerReferralName: "Welsh Tourism Board",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-8",
    name: "Sophie Turner",
    companyName: "",
    phones: ["+44 191 277 8899"],
    emails: ["sophie.turner@gmail.com"],
    addresses: ["15 Grey Street, Newcastle upon Tyne NE1 6EE"],
    tags: ["residential", "repeat"],
    leadSource: "referral",
    partnerReferralName: "Neighbour",
    status: "Maintenance",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-9",
    name: "James Clark",
    companyName: "Clark & Associates",
    phones: ["+44 131 226 7000"],
    emails: ["james@clarkassociates.co.uk"],
    addresses: ["50 Princes Street, Edinburgh EH2 2DQ"],
    tags: ["commercial"],
    leadSource: "cold_outreach",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-10",
    name: "Lucy Bennett",
    companyName: "Bennett Landscapes",
    phones: ["+44 117 929 1122"],
    emails: ["lucy@bennettlandscapes.co.uk"],
    addresses: ["4 Clifton Down, Bristol BS8 1AF"],
    tags: ["residential", "design", "premium"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-11",
    name: "Daniel Wright",
    companyName: "",
    phones: ["+44 115 948 3344"],
    emails: ["daniel.wright@yahoo.co.uk"],
    addresses: ["78 Market Square, Nottingham NG1 6HW"],
    tags: ["residential"],
    leadSource: "referral",
    partnerReferralName: "Local Council",
    status: "Past",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-12",
    name: "Chloe Adams",
    companyName: "Adams Property Management",
    phones: ["+44 121 643 5566"],
    emails: ["chloe@adamsproperty.co.uk"],
    addresses: ["100 Hagley Road, Birmingham B16 8LT"],
    tags: ["commercial", "repeat"],
    leadSource: "LinkedIn",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-13",
    name: "Thomas King",
    companyName: "",
    phones: ["+44 161 834 7788"],
    emails: ["thomas.king@hotmail.com"],
    addresses: ["33 King Street, Manchester M2 4AG"],
    tags: ["residential"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-14",
    name: "Hannah Phillips",
    companyName: "Phillips Nurseries",
    phones: ["+44 1273 609 990"],
    emails: ["hannah@phillipsnurseries.co.uk"],
    addresses: ["12 Lewes Road, Brighton BN2 3QE"],
    tags: ["commercial", "premium"],
    leadSource: "partner",
    partnerReferralName: "Horticulture Association",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-15",
    name: "William Foster",
    companyName: "",
    phones: ["+44 23 8063 2211"],
    emails: ["will.foster@gmail.com"],
    addresses: ["45 Ocean Village, Southampton SO14 3QF"],
    tags: ["residential", "repeat"],
    leadSource: "referral",
    partnerReferralName: "",
    status: "Maintenance",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-16",
    name: "Grace Morgan",
    companyName: "Morgan Estates",
    phones: ["+44 29 2038 5544"],
    emails: ["grace@morganestates.co.uk"],
    addresses: ["7 St Mary Street, Cardiff CF10 1AT"],
    tags: ["residential", "premium"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-17",
    name: "Jack Cooper",
    companyName: "Cooper Logistics",
    phones: ["+44 114 273 6677"],
    emails: ["jack@cooperlogistics.co.uk"],
    addresses: ["22 Sheaf Street, Sheffield S1 2BP"],
    tags: ["commercial"],
    leadSource: "cold_outreach",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-18",
    name: "Amelia Scott",
    companyName: "",
    phones: ["+44 116 255 8899"],
    emails: ["amelia.scott@outlook.com"],
    addresses: ["55 Granby Street, Leicester LE1 1DW"],
    tags: ["residential"],
    leadSource: "other",
    partnerReferralName: "",
    status: "Lead",
    reviewStatus: "Pending",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "seed-19",
    name: "George Hill",
    companyName: "Hill Construction",
    phones: ["+44 117 244 0011"],
    emails: ["george@hillconstruction.co.uk"],
    addresses: ["3 Queen Square, Bristol BS1 4ND"],
    tags: ["commercial", "repeat"],
    leadSource: "referral",
    partnerReferralName: "Builders Association",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: false,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
  {
    id: "seed-20",
    name: "Isabella Ward",
    companyName: "",
    phones: ["+44 20 7499 2233"],
    emails: ["isabella.ward@gmail.com"],
    addresses: ["28 Marylebone High Street, London W1U 4PX"],
    tags: ["residential", "premium"],
    leadSource: "website",
    partnerReferralName: "",
    status: "Active",
    reviewStatus: "Approved",
    seasonalServiceEligibility: true,
    notes: [],
    timeline: [],
    attachments: [],
    createdAt: lastMonth,
    updatedAt: now,
  },
]
