import type { Project } from "@/lib/project-types"

const now = new Date().toISOString()
const lastWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()

/** Seed projects linked to customer seed ids (seed-1, seed-2, ...) */
export const PROJECT_SEED_DATA: Project[] = [
  {
    id: "proj-seed-1",
    name: "Kensington Lawn & Garden",
    customerId: "seed-1",
    projectType: "New Construction",
    status: "In Progress",
    priority: "High",
    propertySize: "0.25 acres",
    estimatedLandscapeSqFt: 8500,
    remainingSqFt: 2000,
    estimatedPropertyValue: 850000,
    terrainType: "Flat with slight slope",
    accessNotes: "Side gate 1.2m wide. No heavy machinery past front.",
    durationEstimate: "3 weeks",
    requiredMaterials: ["Topsoil", "Turf", "Mulch", "Edging"],
    equipment: ["Lawn mower", "Edger", "Spreader"],
    assignedCrew: "Crew A",
    dependencyProjectIds: [],
    timeline: [
      { id: "m1", type: "deposit_payment", title: "Deposit received", dueDate: lastWeek, completedAt: lastWeek, order: 0 },
      { id: "m2", type: "material_ordering", title: "Materials ordered", dueDate: null, completedAt: null, order: 1 },
      { id: "m3", type: "crew_assignment", title: "Crew assigned", dueDate: null, completedAt: now, order: 2 },
      { id: "m4", type: "work_phase", title: "Main installation", dueDate: null, completedAt: null, order: 3 },
      { id: "m5", type: "final_walkthrough", title: "Final walkthrough", dueDate: null, completedAt: null, order: 4 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "proj-seed-2",
    name: "Deansgate Commercial Landscaping",
    customerId: "seed-2",
    projectType: "Maintenance",
    status: "Awaiting Deposit",
    priority: "Medium",
    propertySize: "0.5 acres",
    estimatedLandscapeSqFt: 12000,
    remainingSqFt: null,
    estimatedPropertyValue: null,
    terrainType: "Paved and planted areas",
    accessNotes: "Loading bay available 8–10am.",
    durationEstimate: "Ongoing monthly",
    requiredMaterials: ["Fertilizer", "Weed control"],
    equipment: ["Mower", "Blower"],
    assignedCrew: "",
    dependencyProjectIds: [],
    timeline: [
      { id: "m2a", type: "deposit_payment", title: "Deposit", dueDate: null, completedAt: null, order: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-seed-3",
    name: "Edgbaston Back Garden",
    customerId: "seed-3",
    projectType: "Remodel",
    status: "Planned",
    priority: "Low",
    propertySize: "Small",
    estimatedLandscapeSqFt: 1500,
    remainingSqFt: 1500,
    estimatedPropertyValue: 250000,
    terrainType: "Level",
    accessNotes: "Narrow passage from front.",
    durationEstimate: "1 week",
    requiredMaterials: ["Gravel", "Plants", "Timber"],
    equipment: ["Wheelbarrow", "Hand tools"],
    assignedCrew: "",
    dependencyProjectIds: [],
    timeline: [
      { id: "m3a", type: "deposit_payment", title: "Deposit", dueDate: null, completedAt: null, order: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "proj-seed-4",
    name: "Chelsea Embankment Design",
    customerId: "seed-4",
    projectType: "Custom",
    status: "Materials Ordered",
    priority: "High",
    propertySize: "0.2 acres",
    estimatedLandscapeSqFt: 6000,
    remainingSqFt: 6000,
    estimatedPropertyValue: 1200000,
    terrainType: "Terraced",
    accessNotes: "Crane access for large specimens.",
    durationEstimate: "4 weeks",
    requiredMaterials: ["Designer plants", "Stone", "Lighting"],
    equipment: ["Mini digger", "Crane"],
    assignedCrew: "Crew B",
    dependencyProjectIds: [],
    timeline: [
      { id: "m4a", type: "deposit_payment", title: "Deposit", dueDate: null, completedAt: null, order: 0 },
      { id: "m4b", type: "material_ordering", title: "Materials ordered", dueDate: null, completedAt: now, order: 1 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
  },
  {
    id: "proj-seed-5",
    name: "Leeds Industrial Park Grounds",
    customerId: "seed-5",
    projectType: "Seasonal Cleanup",
    status: "Scheduled",
    priority: "Medium",
    propertySize: "1 acre",
    estimatedLandscapeSqFt: 20000,
    remainingSqFt: null,
    estimatedPropertyValue: null,
    terrainType: "Mixed",
    accessNotes: "24/7 access with prior notice.",
    durationEstimate: "2 days",
    requiredMaterials: ["Mulch", "Seasonal plants"],
    equipment: ["Mower", "Chipper"],
    assignedCrew: "Crew C",
    dependencyProjectIds: [],
    timeline: [
      { id: "m5a", type: "deposit_payment", title: "Deposit", dueDate: null, completedAt: null, order: 0 },
      { id: "m5b", type: "crew_assignment", title: "Crew assigned", dueDate: null, completedAt: null, order: 1 },
    ],
    createdAt: lastWeek,
    updatedAt: now,
  },
]
